compliment diary 리뷰 수정
ComplimentDiary/compliment-diary-backend pull request #2
Opened 2024-10-02 08:19 UTC by cyeji

2024-10-04 07:32 UTC, cyeji commented on src/test/java/com/sgyj/complimentdiary/modules/controller/UserControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.post("/api/users/register")
@seunggulee1007 회원가입 시도 시
No qualifying bean of type 'com.sgyj.complimentdiary.modules.service.DiaryService' available: expected at least 1 bean which qualifies as autowire candidate.
해당에러 발생합니다

2024-10-06 13:07 UTC, seunggulee1007 commented on src/test/java/com/sgyj/complimentdiary/modules/controller/UserControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.post("/api/users/register")
리뷰어를 지정해 주세요.

2024-10-06 13:08 UTC, seunggulee1007 commented on src/test/java/com/sgyj/complimentdiary/modules/controller/UserControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.post("/api/users/register")
![image](https://github.com/user-attachments/assets/3218cca5-d0be-476e-acca-fc449b95bcbe)
어노테이션을 바꾸면 해결 됩니다.

2024-10-06 13:21 UTC, seunggulee1007 approved these changes

2024-10-06 13:21 UTC, seunggulee1007 commented on src/main/java/com/sgyj/complimentdiary/modules/controller/DiaryController.java
>      @PostMapping("/register")
restful 규칙에 의해서 행위는 메서드 만으로 표시됩니다.
따라서 Get, Post, Patch, Delete, Put 등으로만 표현해 주세요

2024-10-06 13:21 UTC, seunggulee1007 commented on src/main/java/com/sgyj/complimentdiary/modules/controller/UserController.java
> +    public ResponseEntity<UserResponse> createUser(@RequestBody @Valid CreateUserRequest request) {
위와 마찬가지 입니다.

2024-10-06 13:21 UTC, seunggulee1007 commented on src/main/java/com/sgyj/complimentdiary/modules/dto/CreateDiaryDto.java
>  public class CreateDiaryDto {
등록과 반환의 값이 다를 수 있으니 객체를 `dto`로 명시하는것 보다는 요청받을때는 `~Request` , 응답할때는 `~Response`로 하는게 어떨까요?

2024-10-06 13:21 UTC, seunggulee1007 commented on src/main/java/com/sgyj/complimentdiary/modules/dto/DiaryResultDto.java
> +        return new DiaryResultDto(memberDiary.getMember().getMemberId(), memberDiary.getDiaryDate(), memberDiary.getDiaryList());
메시지 체인이라는 리팩토링 대상 코드가 있습니다.
레퍼런스를 따라 계속해서 메소드 호출이 이어지는 코드인데, 체인 중 일부가 변경되면 클라이언트의 코드도 변경해야 하는 단점과, 해당 코드의 클라이언트가 코드 체인을 모두 이해해야하는 단점이 있습니다.

따라서 위임 숨기기를 통해 메시지 체인을 캡슐화 할 수 잇습니다.

ex) memberDiary.getMemberId()
``` java
// Member.class
public Long getMemberId() {
    if(member == null) return null;
    return member.getMemberId();
}
```

2024-10-07 13:46 UTC, seunggulee1007 requested changes

2024-10-07 13:46 UTC, seunggulee1007 commented on src/main/java/com/sgyj/complimentdiary/modules/dto/UserResponse.java
>  public class UserResponse {
회원 도메인은 Member로 바뀌었는데 이 객체는 여전히 User인가요 ?

2024-10-07 13:46 UTC, seunggulee1007 commented on src/main/java/com/sgyj/complimentdiary/modules/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, String> {
pk 가 통일 될 필요가 있어 보입니다.
위의 MemberDiaryRepository는 Long인데 여기는 String이네요.
pk 의 조건중 하나는 정렬이 가능해야 한다는 점입니다.

2024-10-07 13:46 UTC, seunggulee1007 commented on src/main/java/com/sgyj/complimentdiary/modules/repository/entity/Member.java
> +    public static Member from(String userId, String username, String password, String email) {
보통 from 메서드는 특정 객체로 부터 만들어지는 메서드 이고, 이렇게 인자로 받는것들은 of 라는 메서드 명을 많이 사용합니다.

2024-10-07 13:46 UTC, seunggulee1007 commented on src/main/resources/application.yml
> +      on-profile: local
spring boot의 기본 프로필은 default가 맞습니다.
굳이 local 로 바꾼 이유가 있을까요?
이렇게 하려면 어플리케이션 구동할 때 마다 프로파일을 지정해 줘야 합니다.

2024-10-08 00:17 UTC, cyeji commented on src/main/java/com/sgyj/complimentdiary/modules/dto/CreateDiaryDto.java
>  public class CreateDiaryDto {
Request,Response로 통일하였습니다

2024-10-08 00:17 UTC, cyeji commented on src/main/java/com/sgyj/complimentdiary/modules/controller/UserController.java
> +    public ResponseEntity<UserResponse> createUser(@RequestBody @Valid CreateUserRequest request) {
변경하였습니다

2024-10-08 00:17 UTC, cyeji commented on src/main/java/com/sgyj/complimentdiary/modules/controller/DiaryController.java
>      @PostMapping("/register")
변경하였습니다

2024-10-08 00:18 UTC, cyeji commented on src/test/java/com/sgyj/complimentdiary/modules/controller/UserControllerTest.java
> +        mockMvc.perform(MockMvcRequestBuilders.post("/api/users/register")
Controller 테스트 정상동작 확인하였습니다!

2024-10-08 00:18 UTC, cyeji commented on src/main/java/com/sgyj/complimentdiary/modules/dto/UserResponse.java
>  public class UserResponse {
Member로 통일하였습니다

2024-10-08 00:23 UTC, cyeji commented on src/main/java/com/sgyj/complimentdiary/modules/repository/entity/Member.java
> +    public static Member from(String userId, String username, String password, String email) {
수정하였습니다

2024-10-08 00:23 UTC, cyeji commented on src/main/resources/application.yml
> +      on-profile: local
수정하였습니다

2024-10-08 00:37 UTC, cyeji commented on src/main/java/com/sgyj/complimentdiary/modules/dto/DiaryResultDto.java
> +        return new DiaryResultDto(memberDiary.getMember().getMemberId(), memberDiary.getDiaryDate(), memberDiary.getDiaryList());
수정하였습니다

2024-10-08 00:38 UTC, cyeji commented on src/main/java/com/sgyj/complimentdiary/modules/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, String> {
Long값으로 변경하였습니다

2024-10-08 01:09 UTC, seunggulee1007 approved these changes
수고하셨습니다 💯

2024-10-08 04:13 UTC, merged